### ISSUE TITLE
Feature request : genericObject plugins compatibility

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/treeview#24]
Hi,

First of all, thanks a lot for your really useful plugins. Having the hardware displayed in a three view from the locations is really a nice feature.

I would like to know if it would be a lot of work to implement compatibility with the "genericobject" plugins? This plugins enables us to add hardware categories in GLPI. For example in our school district, instead of adding all our projectors and interactive boards under the "peripherals" category, we add them under a "Projector" hardware category.

Having compatibility with both plugins would enable us to view this "Projector" category with the same three view as others computers, monitors, peripherals, printers, etc...

Thanks a lot
Francois

**Comment by stonebuzz** [comment]
hi @fralla2 link between genericobject and treeview is already done.

Genericobject need to be defined as "Can use treeview" and need native location field.

Treeview plugin need to be enabled.
Best regards

**Comment by fralla2** [comment]
Thanks for pointing this out to me. I had missed this option on the GenericObject plugins.  One other question if I may : 

As soon as I activate this option, the threeview stops working correctly when selecting a room that contains these generic objects..

You can see on my screenshots, for example, for room E001 -> 2060, the display is done connectly since there's no genericobject in that room but if I choose E001 -> 2010 that contains a genericobject (projector), the threeview reload with an empty page and nothing is displayed.

I've checked the php and mysql logs but no errors display there.....

![glpi-plugins-arborescence-001](https://user-images.githubusercontent.com/38400135/77433973-828d5f80-6db6-11ea-96df-93b9a53f37aa.png)
![glpi-plugins-arborescence-002](https://user-images.githubusercontent.com/38400135/77433983-85885000-6db6-11ea-986a-381cef133f89.png)
![glpi-plugins-arborescence-003](https://user-images.githubusercontent.com/38400135/77433984-87521380-6db6-11ea-8d08-ba6735cfcde7.png)
![glpi-plugins-arborescence-004](https://user-images.githubusercontent.com/38400135/77433989-891bd700-6db6-11ea-988b-7c3f061e1f6d.png)


The source code on the blank page is the following : 

`<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Frameset//EN'
             'http://www.w3.org/TR/html4/frameset.dtd'>
<html><head><title>GLPI - Arborescence</title><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><meta http-equiv='Expires' content='Fri, Jun 12 1981 08:20:00 GMT'>
<meta http-equiv='Pragma' content='no-cache'>
<meta http-equiv='Cache-Control' content='no-cache'>
<link rel='stylesheet' type='text/css' media='print' href='/glpi/css/print.css' >
<link rel='shortcut icon' type='images/x-icon' href='/glpi/pics/favicon.ico' >
<script type="text/javascript">if (top != self)top.location = self.location;</script></head><frameset cols='250,*' border='0'><frame src='/glpi/plugins/treeview/left.php' name='left' scrolling='yes'><frame src='/glpi/front/central.php' name='right'><noframes><body><p><a href='/glpi/front/central.php'>GLPI</a></p></body></noframes></frameset></html>`

Thanks
Francois

**Comment by fralla2** [comment]
Github stripped some of the code.  Here it is in screen shot

![glpi-plugins-arborescence-005](https://user-images.githubusercontent.com/38400135/77434184-ddbf5200-6db6-11ea-8794-e129354a2154.png)


Thanks
Francois

**Comment by stonebuzz** [comment]
Hi @fralla2 can you test this PR -> https://github.com/pluginsGLPI/genericobject/pull/273 
it's genericobject bug not treeview

I found this in log

```shell
2020/03/25 08:11:48 [error] 1896#1896: *185 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method PluginGenericobjectAntenne::getObjectSearchOptions() in /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/plugins/genericobject/inc/object.class.php:117
Stack trace:
#0 /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/inc/plugin.class.php(1162): PluginGenericobjectObject::getParentNodeSearchUrl(Array)
#1 /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/plugins/treeview/inc/config.class.php(458): Plugin::doHookFunction('treeview_search...', Array)
#2 /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/plugins/treeview/inc/config.class.php(301): PluginTreeviewConfig->getNodesFromDb()
#3 /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/plugins/treeview/left.php(69): PluginTreeviewConfig->buildTreeview()
#4 {main}
  thrown in /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/plugins/genericobject/inc/object.class.php on line 117" while reading response header from upstream, client: 127.0.0.1, server: dev.local, request: "GET /GLPI/9.4-bugfixes/plugins/treeview/left.php?nodes=1.0&openedType= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9972", host: "dev.local", referrer: "http://dev.local/GLPI/9.4-bugfixes/plugins/treeview/left.php"
```

**Comment by fralla2** [comment]
I've just tested the fix on my system and I can confirm it working. Thanks a lot for this quick fix :)

Francois
